language: node_js

node_js:
  - 10.15.1

os:
  - linux
  - osx

install:
  - npm install -g esy@0.5.6
  - esy make build-native

test:
  - esy test

cache:
  timeout: 360
  directories:
    - '$HOME/.esy/'
